//
// Created by icpc on 2020/11/26.
//

#ifndef DBENGINE_DBEDEFINES_H
#define DBENGINE_DBEDEFINES_H

#define CLOSE_SUCCESS 1
#define CLOSE_FAILED 0

#define FIND_SUCCESS 1
#define FIND_FAILED 0

#define ERASE_SUCCESS 1
#define ERASE_FAILED 0

#define INSERT_SUCCESS 1
#define INSERT_FAILED 0

#define NEXT_SUCCESS 1
#define NEXT_FAILED 0

#define RESET_SUCCESS 1
#define RESET_FAILED 0

#define CREATE_SUCCESS 1
#define CREATE_FAILED 0

#define REORGANIZE_SUCCESS 1
#define REORGANIZE_FAILED 0

#define SET_COOKIES_SUCCESS 1
#define SET_COOKIES_FAILED 0


#endif //DBENGINE_DBEDEFINES_H
