name:                compiler
version:             0.1.0.0

ghc-options:
  - -Wall

dependencies:
  - base >= 4.7 && < 5
  - mtl == 2.2.2
  - containers == 0.6.2.1

library:
  source-dirs:
    - src/Parser
    - src/CodeGenerator

executables:
  NMSqL:
    main: src/FFI/FFI.hs
    c-sources:
      - ../shell.c
    dependencies:
      - compiler
    extra-lib-dirs:
      ../../backend/lib
    extra-libraries:
      - DbEngine
      - VirtualMachine
    ghc-options:
      - -no-hs-main
      - -static

tests:
  module-test:
    main:         Main.hs
    source-dirs:  src/Test/CodeGenerator
    dependencies:
      - compiler
      - HUnit == 1.6.0.0
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N