name:                compiler
version:             0.1.0.0

ghc-options:
  - -Wall

dependencies:
  - base >= 4.7 && < 5
  - mtl == 2.2.2
  - containers == 0.6.2.1

library:
  source-dirs:
    - src/Parser
    - src/CodeGenerator
    - src/FFI

executables:
  libCompiler.so:
    main: src/FFI/FFI.hs
    dependencies:
      - compiler
    ghc-options:
      - -no-hs-main
      - -fPIC
      - -shared
      - -dynamic

tests:
  module-test:
    main:         Main.hs
    source-dirs:  src/Test/CodeGenerator
    dependencies:
      - compiler
      - HUnit == 1.6.0.0
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N